name: Lint Python Code

on:
  pull_request:
    branches:
      - development  # Trigger this workflow on pull requests to the 'development' branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out the repository's code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use Python version 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint  # Install your preferred linter

    - name: Run pylint
      run: |
        pylint **/*.py  # Run pylint on all Python files



# Explanation of the YAML File:
# name: Lint Python Code: The name of the workflow that will appear in GitHub.
# on: pull_request: This workflow will run whenever a pull request is made to the development branch.
# runs-on: ubuntu-latest: Specifies the environment (Ubuntu) where the job will run.
# steps:
# Checkout repository: Fetches your repository’s code so the workflow can run on it.
# Set up Python: Installs the specified version of Python.
# Install dependencies: Installs pylint (you can change this to flake8, black, or any other linter you use).
# Run pylint: Runs the linter on all Python files.
# You can modify this configuration to suit your needs, such as using a different linter like flake8 or black.
